<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js" type="text/javascript" charset="UTF-8" data-domain-script= 7e6a6e16-7c8d-4b32-9b7e-613a9640f50c ></script>
    <script type="text/javascript">
      // This function is executed any time OneTrust updates the privacy groups.
      // window.dataLayer contains a list of events related to OneTrust. To implement
      // the auto-refresh logic, the easiest way is to detect the previous state and the
      // new one. If groups have changed, we need to reload the site.
      //
      // Note that this code is not parsed by webpack, so I'm gonna use the ECMA5
      function OptanonWrapper() {
        // Get the events that informs about a change
        var events = window.dataLayer.filter(function(element) {
          return element.event === "OneTrustGroupsUpdated" && element.OnetrustActiveGroups != null;
        });
        var latestEvent = events[events.length - 1];
        var previousEvent = events.length === 1 ? latestEvent : events[events.length - 2];

        // Perform the push required by OneTrust
        { window.dataLayer.push({ event: 'OneTrustGroupsUpdated' }); }

        // Confirm if we need to reload
        if (latestEvent.OnetrustActiveGroups != previousEvent.OnetrustActiveGroups) {
          location.reload();
        }
      }
    </script>
    <!-- Always force latest IE rendering engine or request Chrome Frame -->
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Use title if it's in the page YAML frontmatter -->
    <title>Download XAMPP</title>

    <meta name="description" content="Download XAMPP for Windows, Linux, and OS X. Older versions of Solaris are also available." />
    <meta name="keywords" content="xampp, apache, php, perl, mysql, windows, linux, osx" />

    <link href="/stylesheets/normalize-ef7858ef.css" rel="stylesheet" type="text/css" /><link href="/stylesheets/all-b63a07a3.css" rel="stylesheet" type="text/css" />
    <link href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />

    <script src="/javascripts/modernizr-6bfc3ff0.js" type="text/javascript"></script>

    <link rel="alternate" type="application/rss+xml" title="Apache Friends RSS Feed" href="/feed.xml" />

    <link href="/images/favicon-18f9bd42.png" rel="icon" type="image/png" />

      <script type="text/plain" class="optanon-category-C0002">
        //<![CDATA[
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
              (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
              })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-76894-1', 'auto');
          ga('send', 'pageview');
        //]]>
      </script>

  </head>

  <body class="download">
    <div id="fb-root"></div>
    <script type="text/plain" class="optanon-category-C0005">
      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=277385395761685";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
    <div class="contain-to-grid">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="/index.html">Apache Friends</a></h1>
          </li>
          <li class="toggle-topbar menu-icon">
            <a href="#">
              <span>Menu</span>
            </a>
          </li>
        </ul>

        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
              <li class="active"><a href="/download.html">Download</a></li>
              <li class=""><a href="/add-ons.html">Add-ons</a></li>
              <li class=""><a href="/hosting.html">Hosting</a></li>
              <li class=""><a href="/community.html">Community</a></li>
              <li class=""><a href="/about.html">About</a></li>
              <li class="has-form">
                <form action="/search.html" method="get">
                <div class="row collapse">
                  <div class="large-8 small-9 columns">
                    <input type="text" name="q" placeholder="Search..">
                  </div>
                  <div class="large-4 small-3 columns">
                    <input type="submit" class="success button expand" value="Search"/>
                  </div>
                </div>
                </form>
              </li>
              <li id="locales" class="has-dropdown">
<a href="#">                  <img src="/images/flags/en-dd9e149e.png" /> EN
</a>                <ul class="dropdown">
                  <li>
<a href="/de/download.html">                      <img src="/images/flags/de-1daf2d67.png" /> DE
</a>                  </li>
                  <li>
<a href="/download.html">                      <img src="/images/flags/en-dd9e149e.png" /> EN
</a>                  </li>
                  <li>
<a href="/es/download.html">                      <img src="/images/flags/es-a88880bf.png" /> ES
</a>                  </li>
                  <li>
<a href="/fr/download.html">                      <img src="/images/flags/fr-0f67f12d.png" /> FR
</a>                  </li>
                  <li>
<a href="/hu/download.html">                      <img src="/images/flags/hu-9a189d12.png" /> HU
</a>                  </li>
                  <li>
<a href="/it/download.html">                      <img src="/images/flags/it-c786c15b.png" /> IT
</a>                  </li>
                  <li>
<a href="/jp/download.html">                      <img src="/images/flags/jp-3c5b1754.png" /> JP
</a>                  </li>
                  <li>
<a href="/pl/download.html">                      <img src="/images/flags/pl-e383eba9.png" /> PL
</a>                  </li>
                  <li>
<a href="/pt_br/download.html">                      <img src="/images/flags/pt_br-e39a2058.png" /> PT BR
</a>                  </li>
                  <li>
<a href="/ro/download.html">                      <img src="/images/flags/ro-f141b663.png" /> RO
</a>                  </li>
                  <li>
<a href="/ru/download.html">                      <img src="/images/flags/ru-24b172c5.png" /> RU
</a>                  </li>
                  <li>
<a href="/tr/download.html">                      <img src="/images/flags/tr-e1821d04.png" /> TR
</a>                  </li>
                  <li>
<a href="/ur/download.html">                      <img src="/images/flags/ur-952dd97a.png" /> UR
</a>                  </li>
                  <li>
<a href="/zh_cn/download.html">                      <img src="/images/flags/zh_cn-9c7185e0.png" /> ZH CN
</a>                  </li>
                  <li>
<a href="/zh_tw/download.html">                      <img src="/images/flags/zh_tw-92fe4f80.png" /> ZH TW
</a>                  </li>
                </ul>
              </li>
          </ul>
        </section>
      </nav>
    </div>

    <div id="wrapper">
      <div class="hero">
  <div class="row">
    <div class="large-12 columns">
      <h1>Download</h1>
    </div>
  </div>
</div>
<div class="row">
  <div class="large-8 columns">
    <p>XAMPP is an easy to install Apache distribution containing MariaDB, PHP, and Perl. Just download and start the installer. It's that easy.</p>
    <ul id="downloads">
        <li id="download-windows">
        <h3><img src="/images/windows-logo-e7e0c87e.png" />XAMPP for <strong>Windows</strong> <span>7.3.29, 7.4.22 &amp; 8.0.9</span></h3>
          <table>
            <tr>
              <th width="25%">Version</th>
              <th width="17.5%" class="show-for-medium-up"></th>
              <th width="20%" class="show-for-medium-up">Checksum</th>
              <th width="25%"></th>
              <th width="12.5%" class="show-for-medium-up">Size</th>
            </tr>
              <tr>
                <td rowspan="1">7.3.29 / PHP 7.3.29</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="windows-notes-a741986901" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="853e3941d493c0ac9eb35617e1b30f29">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="6c2e7a2786489ce754ce0473a3611c62622b1820">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/7.3.29/xampp-windows-x64-7.3.29-2-VC15-installer.exe">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">158 Mb</td>
              </tr>
              <tr>
                <td rowspan="1">7.4.22 / PHP 7.4.22</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="windows-notes-b32f0ac5d9" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="b3eba2d5e1c7978dbd69006dce52e5ee">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="dcd7597e5e1a95ae0333045edfa9bacae0805f11">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/7.4.22/xampp-windows-x64-7.4.22-0-VC15-installer.exe">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">159 Mb</td>
              </tr>
              <tr>
                <td rowspan="1">8.0.9 / PHP 8.0.9</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="windows-notes-f828e8e113" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="ef4973769725452aec7380bdfb89c71b">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="b8169444ddd0f2650356a6b1632be8e7dc6daf15">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/8.0.9/xampp-windows-x64-8.0.9-0-VS16-installer.exe">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">160 Mb</td>
              </tr>
          </table>
          <ul class="inline-list">
            <li><a data-dropdown="windows-requirements" href="#">Requirements</a></li>
            <li><a href="/add-ons.html">Add-ons</a></li>
            <li><a href="http://sourceforge.net/projects/xampp/files/">More Downloads &raquo;</a></li>
          </ul>
            <div class="notes" id="windows-notes-a741986901" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 7.3.29, phpMyAdmin 5.1.1, OpenSSL 1.1.1, XAMPP Control Panel 3.2.4, Webalizer 2.23-04, Mercury Mail Transport System 4.63, FileZilla FTP Server 0.9.41, Tomcat 8.5.69 (with mod_proxy_ajp as connector), Strawberry Perl 5.32.1.1 Portable</p>
            </div>
            <div class="notes" id="windows-notes-b32f0ac5d9" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 7.4.22, phpMyAdmin 5.1.1, OpenSSL 1.1.1, XAMPP Control Panel 3.2.4, Webalizer 2.23-04, Mercury Mail Transport System 4.63, FileZilla FTP Server 0.9.41, Tomcat 8.5.69 (with mod_proxy_ajp as connector), Strawberry Perl 5.32.1.1 Portable</p>
            </div>
            <div class="notes" id="windows-notes-f828e8e113" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 8.0.9, phpMyAdmin 5.1.1, OpenSSL 1.1.1, XAMPP Control Panel 3.2.4, Webalizer 2.23-04, Mercury Mail Transport System 4.63, FileZilla FTP Server 0.9.41, Tomcat 8.5.69 (with mod_proxy_ajp as connector), Strawberry Perl 5.32.1.1 Portable</p>
            </div>
          <div class="notes" id="windows-requirements" data-dropdown-content>
              <p>Windows 2008, 2012, Vista, 7, 8 (Important: XP or 2003 not supported)</p>
          </div>
            <p>Windows XP or 2003 are not supported. You can download a compatible version of XAMPP for these platforms <a href="http://sourceforge.net/projects/xampp/files/XAMPP%20Windows/1.8.2/">here</a>.</p>
        </li>
        <li id="download-linux">
        <h3><img src="/images/linux-logo-f6a47353.png" />XAMPP for <strong>Linux</strong> <span>7.3.29, 7.4.22 &amp; 8.0.9</span></h3>
          <table>
            <tr>
              <th width="25%">Version</th>
              <th width="17.5%" class="show-for-medium-up"></th>
              <th width="20%" class="show-for-medium-up">Checksum</th>
              <th width="25%"></th>
              <th width="12.5%" class="show-for-medium-up">Size</th>
            </tr>
              <tr>
                <td rowspan="1">7.3.29 / PHP 7.3.29</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="linux-notes-744aafc281" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="8291e69baff5c80becf545b6ee43913a">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="5707b8c52c9d5dc3bf82294f700fa02440f274f9">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/7.3.29/xampp-linux-x64-7.3.29-2-installer.run">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">151 Mb</td>
              </tr>
              <tr>
                <td rowspan="1">7.4.22 / PHP 7.4.22</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="linux-notes-adf84ea7ae" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="ce1916379efc00015e8dfc282de1c6ba">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="fd51e3cc2fbc3285701ad3e7a1f9f7aeb70b39b2">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/7.4.22/xampp-linux-x64-7.4.22-0-installer.run">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">151 Mb</td>
              </tr>
              <tr>
                <td rowspan="1">8.0.9 / PHP 8.0.9</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="linux-notes-08d069fb1f" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="a2865fdb3b45ed17787df5283b2ae7eb">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="740158c24b2a4566b18c9bc9c12fce7cc32ae661">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/8.0.9/xampp-linux-x64-8.0.9-0-installer.run">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">154 Mb</td>
              </tr>
          </table>
          <ul class="inline-list">
            <li><a data-dropdown="linux-requirements" href="#">Requirements</a></li>
            <li><a href="/add-ons.html">Add-ons</a></li>
            <li><a href="http://sourceforge.net/projects/xampp/files/">More Downloads &raquo;</a></li>
          </ul>
            <div class="notes" id="linux-notes-744aafc281" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 7.3.29 + SQLite 2.8.17/3.36.0 + multibyte (mbstring) support, Perl 5.32.1, ProFTPD 1.3.6, phpMyAdmin 5.1.1, OpenSSL 1.1.1k, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4</p>
            </div>
            <div class="notes" id="linux-notes-adf84ea7ae" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 7.4.22 + SQLite 2.8.17/3.36.0 + multibyte (mbstring) support, Perl 5.32.1, ProFTPD 1.3.6, phpMyAdmin 5.1.1, OpenSSL 1.1.1k, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4</p>
            </div>
            <div class="notes" id="linux-notes-08d069fb1f" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 8.0.9 & PEAR + SQLite 2.8.17/3.36.0 + multibyte (mbstring) support, Perl 5.32.1, ProFTPD 1.3.6, phpMyAdmin 5.1.1, OpenSSL 1.1.1k, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4</p>
            </div>
          <div class="notes" id="linux-requirements" data-dropdown-content>
              <p>Most all distributions of Linux are supported, including Debian, RedHat, CentOS, Ubuntu, Fedora, Gentoo, Arch, SUSE.</p>
          </div>
        </li>
        <li id="download-apple">
        <h3><img src="/images/apple-logo-f4325ff1.png" />XAMPP for <strong>OS X</strong> <span>7.3.29, 7.4.22, 8.0.9, 7.3.29, 7.4.22 &amp; 8.0.9</span></h3>
          <table>
            <tr>
              <th width="25%">Version</th>
              <th width="17.5%" class="show-for-medium-up"></th>
              <th width="20%" class="show-for-medium-up">Checksum</th>
              <th width="25%"></th>
              <th width="12.5%" class="show-for-medium-up">Size</th>
            </tr>
              <tr>
                <td rowspan="1">7.3.29 / PHP 7.3.29</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="apple-notes-6d0892eed7" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="6f3340a0719190f028540a0c4487914f">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="a2a8ca67b8bc2ee72b215de909fee81ca16f0b3a">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/7.3.29/xampp-osx-7.3.29-2-installer.dmg">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">163 Mb</td>
              </tr>
              <tr>
                <td rowspan="1">7.4.22 / PHP 7.4.22</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="apple-notes-0301fc41e7" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="f62d8c94c2f261886107aa9f39499fc1">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="be933f09fa5af4371e1d3773e54a1faf0aea598c">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/7.4.22/xampp-osx-7.4.22-0-installer.dmg">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">163 Mb</td>
              </tr>
              <tr>
                <td rowspan="1">8.0.9 / PHP 8.0.9</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="apple-notes-693c9f3b1e" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="08e701831e66abf4a6544de8ab3e077c">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="e8628a9f03b3a4b440d41ef89aa18194d53ed852">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/8.0.9/xampp-osx-8.0.9-0-installer.dmg">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">164 Mb</td>
              </tr>
              <tr>
                <td rowspan="1">7.3.29 / PHP 7.3.29</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="apple-notes-1f188d619d" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="51ff032f73889d18fd0f9c872f964f93">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="f59924576025ba2dd6ffa135068b22452e8a5d46">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/7.3.29/xampp-osx-7.3.29-2-vm.dmg">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">361 Mb</td>
              </tr>
              <tr>
                <td rowspan="1">7.4.22 / PHP 7.4.22</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="apple-notes-18609e1a16" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="3fd69319a609aa674881d6e37a8b4d20">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="e6a6cb4fee9f4ab0cd52c9ab2196eae6e377c535">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/7.4.22/xampp-osx-7.4.22-0-vm.dmg">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">360 Mb</td>
              </tr>
              <tr>
                <td rowspan="1">8.0.9 / PHP 8.0.9</td>
                  <td class="show-for-medium-up" rowspan="1"><a data-dropdown="apple-notes-ecba418b4d" href="#">What's Included?</a></td>
                  
                    <td class="show-for-medium-up">
                      <ul class="inline-list">
                        <li><span data-tooltip class="has-tip" title="30f27e13b1bd8e3fb38487baa536b818">md5</span></li>
                        <li><span data-tooltip class="has-tip" title="6796589a980b7e3a4751cedae596021f9aafd798">sha1</span></li>
                      </ul>
                    </td>
                    <td class="text-right">
                      <a class="button" data-delayed-href="/download_success.html" target="_blank" href="https://www.apachefriends.org/xampp-files/8.0.9/xampp-osx-8.0.9-0-vm.dmg">Download (64 bit)</a>
                    </td>
                    <td class="show-for-medium-up">360 Mb</td>
              </tr>
          </table>
          <ul class="inline-list">
            <li><a data-dropdown="apple-requirements" href="#">Requirements</a></li>
            <li><a href="/add-ons.html">Add-ons</a></li>
            <li><a href="http://sourceforge.net/projects/xampp/files/">More Downloads &raquo;</a></li>
          </ul>
            <div class="notes" id="apple-notes-6d0892eed7" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 7.3.29 + SQLite 2.8.17/3.36.0 + multibyte (mbstring) support, Perl 5.32.1, ProFTPD 1.3.6, phpMyAdmin 5.1.1, OpenSSL 1.1.1k, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4</p>
            </div>
            <div class="notes" id="apple-notes-0301fc41e7" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 7.4.22 + SQLite 2.8.17/3.36.0 + multibyte (mbstring) support, Perl 5.32.1, ProFTPD 1.3.6, phpMyAdmin 5.1.1, OpenSSL 1.1.1k, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4</p>
            </div>
            <div class="notes" id="apple-notes-693c9f3b1e" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 8.0.9 & PEAR + SQLite 2.8.17/3.36.0 + multibyte (mbstring) support, Perl 5.32.1, ProFTPD 1.3.6, phpMyAdmin 5.1.1, OpenSSL 1.1.1k, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4</p>
            </div>
            <div class="notes" id="apple-notes-1f188d619d" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 7.3.29 + SQLite 2.8.17/3.36.0 + multibyte (mbstring) support, Perl 5.32.1, ProFTPD 1.3.6, phpMyAdmin 5.1.1, OpenSSL 1.1.1k, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4</p>
            </div>
            <div class="notes" id="apple-notes-18609e1a16" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 7.4.22 + SQLite 2.8.17/3.36.0 + multibyte (mbstring) support, Perl 5.32.1, ProFTPD 1.3.6, phpMyAdmin 5.1.1, OpenSSL 1.1.1k, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4</p>
            </div>
            <div class="notes" id="apple-notes-ecba418b4d" data-dropdown-content>
              <p><strong>Includes:</strong> Apache 2.4.48, MariaDB 10.4.20, PHP 8.0.9 & PEAR + SQLite 2.8.17/3.36.0 + multibyte (mbstring) support, Perl 5.32.1, ProFTPD 1.3.6, phpMyAdmin 5.1.1, OpenSSL 1.1.1k, GD 2.2.5, Freetype2 2.4.8, libpng 1.6.37, gdbm 1.8.3, zlib 1.2.11, expat 2.0.1, Sablotron 1.0.3, libxml 2.0.1, Ming 0.4.5, Webalizer 2.23-05, pdf class 0.11.7, ncurses 5.9, pdf class 0.11.7, mod_perl 2.0.11, FreeTDS 0.91, gettext 0.19.8.1, IMAP C-Client 2007e, OpenLDAP (client) 2.4.48, mcrypt 2.5.8, mhash 0.9.9.9, cUrl 7.53.1, libxslt 1.1.33, libapreq 2.13, FPDF 1.7, ICU4C Library 66.1, APR 1.5.2, APR-utils 1.5.4</p>
            </div>
          <div class="notes" id="apple-requirements" data-dropdown-content>
              <p>Mac OS X 10.6 or later.</p>
          </div>
        </li>
    </ul>
    <h2>Add-ons</h2>
    <hr />
      <div>
    <h3><a name="xampp-applications">Applications</a></h3>
    <p>Bitnami provides a free all-in-one tool to install WordPress on top of XAMPP.</p>
    <ul id="stack-list">
        <li>
<a href="//bitnami.com/stack/xampp#wordpress">          <img data-2x="//bitnami.com/assets/stacks/wordpress/img/wordpress-stack-220x234.png" width="110" height="117" alt="WordPress" src="//bitnami.com/assets/stacks/wordpress/img/wordpress-stack-110x117.png" />
          <span>WordPress</span>
          <span class="type">Blog</span>
</a>        </li>
    </ul>
  </div>

    <div class="right">
      <a class="button small" href="/add-ons.html">XAMPP Add-ons &rarr;</a>
    </div>
  </div>
  <div class="large-4 columns">
    <aside>
      <h4>Documentation/FAQs</h4>
      <p>There is no real manual or handbook for XAMPP. We wrote the documentation in the form of FAQs. Have a burning question that's not answered here? Try the <a href="https://community.apachefriends.org">Forums</a> or <a href="http://stackoverflow.com/search?q=xampp">Stack Overflow</a>.</p>
      <ul>
        <li><a href="/faq_linux.html">Linux FAQs</a></li>
        <li><a href="/faq_windows.html">Windows FAQs</a></li>
        <li><a href="/faq_osx.html">OS X FAQs</a></li>
        <li><a href="/faq_stackman.html">OS X XAMPP-VM FAQs</a></li>
      </ul>
      <h4>Add-ons</h4>
<a href="/add-ons.html">          <img width="60" data-2x="/images/stack-icons@2x-e9a2dc4a.png" src="/images/stack-icons-40cf11c8.png" />
</a>      <p>Bitnami provides a free all-in-one tool to install WordPress on top of XAMPP. Visit <a href="https://bitnami.com/stack/xampp">Bitnami XAMPP</a> to download the installer.</p>
    </aside>
  </div>
</div>

    </div>

    <footer>
      <div class="row">
        <div class="large-16 columns">
          <div class="row">
            <div class="large-14 columns">
              <ul class="social">
  <li class="twitter"><a href="https://twitter.com/apachefriends">Follow us on Twitter</a></li>
  <li class="facebook"><a href="https://www.facebook.com/we.are.xampp">Like us on Facebook</a></li>
  <li class="google"><a href="https://plus.google.com/+xampp/posts">Add us to your G+ Circles</a></li>
</ul>

              <ul class="inline-list">
                <li><a href="https://www.apachefriends.org/blog.html">Blog</a></li>
                <li><a href="https://www.vmware.com/help/privacy.html">Privacy Policy</a></li>
                <li><a href="https://www.vmware.com/help/legal.html">Terms of Use</a></li>
                <li><a href="https://www.vmware.com/help/privacy/california-privacy-rights.html">Your California Privacy Rights</a></li>
                <li>
<a target="_blank" href="http://www.fastly.com/">                    CDN provided by
                    <img width="48" data-2x="/images/fastly-logo@2x-dad6aac3.png" src="/images/fastly-logo-08360cb5.png" />
</a>                </li>
                <li>
                  <p>Copyright (c) 2021, VMware</p>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <button id="ot-sdk-btn" class="ot-sdk-show-settings"> Cookie Settings</button>
    <!-- JS Libraries -->
    <script src="//code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="/javascripts/all-d8620939.js" type="text/javascript"></script>
  </body>
</html>
